version: "3.5"

volumes:
  user_postgres_data:
    driver: local
  post_postgres_data:
    driver: local
  minio_data:
    driver: local
  cache:
    driver: local

services:
  nginx:
    container_name: realworld-nginx
    restart: always
    image: nginx:stable
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../src/ms-user/:/var/www/ms-user"
      - "../src/ms-post/:/var/www/ms-post"

  s3:
    container_name: realworld-s3
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    volumes:
      - minio_data:/data
    networks:
      - default

  ms_user_php:
    container_name: realworld-ms-user-php
    restart: always
    build:
      target: ${TARGET_VERSION_PHP}
      args:
        user: ${USER}
        uid: ${USER_ID}
      context: ../src/ms-user
      dockerfile: Docker/Dockerfile
    volumes:
      - "../src/ms-user/:/var/www/ms-user/"
    environment:
      COMPOSER_MEMORY_LIMIT: ${COMPOSER_MEMORY_LIMIT}
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - default
    extra_hosts:
      - host.docker.internal:${XDEBUG_REMOTE_HOST}

  ms_user_db:
    container_name: realworld-ms-user-db
    restart: always
    image: postgres:9.6
    env_file:
      - "../src/ms-user/.env"
    volumes:
      - "user_postgres_data:/var/lib/postgresql/data"
    networks:
        - default

  ms_post_php:
    container_name: realworld-ms-post-php
    restart: always
    build:
      target: ${TARGET_VERSION_PHP}
      args:
        user: ${USER}
        uid: ${USER_ID}
      context: ../src/ms-post
      dockerfile: Docker/Dockerfile
    volumes:
      - "../src/ms-post/:/var/www/ms-post/"
    environment:
      COMPOSER_MEMORY_LIMIT: ${COMPOSER_MEMORY_LIMIT}
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - default
    extra_hosts:
      - host.docker.internal:${XDEBUG_REMOTE_HOST}

  ms_post_db:
    container_name: realworld-ms-post-db
    restart: always
    image: postgres:9.6
    env_file:
      - "../src/ms-post/.env"
    volumes:
      - "user_postgres_data:/var/lib/postgresql/data"
    networks:
        - default
  cache:
    container_name: realworld-cache
    restart: always
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    command: "redis-server --save 20 1 --loglevel debug --requirepass ${REDIS_PASSWORD}"
    volumes:
      - cache:/data

networks:
  default:
    name: realworld_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}
